name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Authenticate to Google Cloud using your service account credentials
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 3. Configure Docker for GCR
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      # 4. Build and push Docker image to GCR
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-raj-app:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-raj-app:latest

      # 5. Setup Terraform (install Terraform)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 6. Initialize Terraform in the gke-terraform directory
      - name: Terraform Init
        working-directory: gke-terraform
        run: terraform init

      # 7. Plan Terraform changes
      - name: Terraform Plan
        working-directory: gke-terraform
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-central1"

      # 8. Apply Terraform configuration (creates/updates your GKE cluster)
      - name: Terraform Apply
        working-directory: gke-terraform
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-central1"

      # 9. Install GKE Auth Plugin manually by downloading it from GitHub releases
      - name: Install GKE Auth Plugin
        run: |
          # Download the plugin archive (update the version if necessary)
          curl -Lo gke-gcloud-auth-plugin.tar.gz https://github.com/GoogleCloudPlatform/gke-gcloud-auth-plugin/releases/download/v0.8.0/gke-gcloud-auth-plugin-linux-amd64.tar.gz
          tar -xzf gke-gcloud-auth-plugin.tar.gz
          chmod +x gke-gcloud-auth-plugin
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/

      # 10. Retrieve GKE cluster credentials so that Helm can communicate with your cluster
      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials hello-raj-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

      # 11. Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # 12. Deploy the application with Helm
      - name: Deploy Application with Helm
        run: |
          helm upgrade --install hello-raj-app helm-chart/hello-raj-app \
            --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-raj-app \
            --set image.tag=latest
